project_id = "zikzuwomznlpgvrftcpf"

[functions.fluxa-chat]
verify_jwt = false

[functions.fluxa-daily-drop]
verify_jwt = true

[functions.generate-stories]
verify_jwt = false

[functions.fluxa-daily-recap]
verify_jwt = false

[functions.fluxa-weekly-awards]
verify_jwt = false

[functions.fluxa-health-check]
verify_jwt = false

[functions.auto-generate-gists]
verify_jwt = false