project_id = "pfkahsyvfgkxnihvaylw"

[functions.text-to-speech]
verify_jwt = false

[functions.generate-gist]
verify_jwt = false

[functions.publish-gist]
verify_jwt = false

[functions.fetch-feed]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.scrape-trends]
verify_jwt = false
